### ISSUE TITLE
Criação de componentes básicos

### ISSUE THREAD

**Issue by brendavsantos** [UnBArqDsw2021-1/2021.1_G02_TaNaMesa_Frontend#5]
## Descrição da issue
Issue destinada a criação de componentes simples muito utilizados no projeto (de acordo com o protótipo de alta fidelidade)

## Componentes a serem criados:
- [ ] Botões do menu lateral
- [x] Navbar
- [x] Item do cardápio
- [x] Modal de login

**Comment by sergiosacj** [comment]
Acabei de adicionar como componentes os

- Botões do menu lateral
![Captura de tela de 2021-09-03 07-44-26](https://user-images.githubusercontent.com/36544528/131993439-1a63f627-5898-4e38-9265-8386e1951d20.png)

- Navbar
![Captura de tela de 2021-09-03 07-46-30](https://user-images.githubusercontent.com/36544528/131993676-e5665df7-6641-495b-9a3f-798ad8794e25.png)
![Captura de tela de 2021-09-03 07-46-45](https://user-images.githubusercontent.com/36544528/131993711-acdd1905-b13a-4fef-8047-4bf518e7c946.png)

- Item do cardápio
![Captura de tela de 2021-09-03 07-47-48](https://user-images.githubusercontent.com/36544528/131993802-71e0c31f-6444-43c6-8db5-3682d5b82f2a.png)

Se não concordarem, por favor editem a issue e mandem os que preferem fazer.

**Comment by sergiosacj** [comment]
Todos os elementos escolhidos foram tirados do fluxo do cliente, que foi o combinado anteriormente.

**Comment by sergiosacj** [comment]
Separação definida:
 
- Botões do menu lateral (Brenda)
- Navbar (Lucas)
- Item do cardápio (Sérgio)

**Comment by emysdias** [comment]
![image](https://user-images.githubusercontent.com/52640974/132845550-8a7ff076-9a8f-4d48-8a92-e8571de8ebee.png)
